# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://example.com
title: Your Site Name
subtitle:
author: Your Name
simple_search: http://google.com/search
description: 

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%a %b %e, %Y"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /jekyll-bootstrap-boilerplate/public
permalink: /:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir:
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides:

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   Amazon S3 Settings    #
# ----------------------- #
bucket:
acl: public-read
cf_distribution_id:

# these have been moved to shell env variables for privacy's sake.
# You can include them here if you don't plan on pushing to a publc repository
# access_key_id:
# secret_access_key:




# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

#####
# NOTE: I don't use most of these, but there still here in case I change my mind
#####

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false

collections:
- gathered_data

